## 异常体系

> Error: 程序无法处理的系统错误, 编译器不做检查
>
> Exception: 程序可以处理的异常, 捕获后可能恢复



> 异常的根类是`java.lang.Throwable`
>
> 其下边有2个子类: `java.lang.Error`和`java.lang.Exception`

![](https://youpaiyun.zongqilive.cn/image/20210127161009.png)



![](https://pic.superbed.cn/item/5da3d71e9dc6d638c6f521a8.jpg)

![](https://pic.superbed.cn/item/5e05c48576085c3289bc0a0f.jpg)



![](https://youpaiyun.zongqilive.cn/image/5da433709dc6d63695016ef7.jpg)















































